# Generated by Django 5.1.3 on 2024-12-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plc_name', models.CharField(max_length=155)),
                ('plc_spec', models.CharField(max_length=200)),
            ],
        ),
    ]
