# Generated by Django 5.1.3 on 2024-12-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=150)),
                ('cat_spec', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Places',
        ),
    ]
